version: '3'
services:
  wiremock:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      --verbose
      --local-response-templating
    ports:
      - "8080:8080"
    
    volumes:
      - ./mappings:/home/wiremock/mappings 
      - ./__files:/home/wiremock/__files
